//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecouverteEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KartinaEntities : DbContext
    {
        public KartinaEntities()
            : base("name=KartinaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Photo> Photo { get; set; }
        public virtual DbSet<PhotoTag> PhotoTag { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
        public virtual DbSet<Vendeur> Vendeur { get; set; }
    }
}
