//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecouverteEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Octopuses
    {
        public int Id { get; set; }
        public int CurrentHealthPoint { get; set; }
        public int MaxHealthPoint { get; set; }
        public int CurrentFoodLevel { get; set; }
        public int MaxFoodLevel { get; set; }
        public int CurrentHygieneLevel { get; set; }
        public int MaxHygieneLevel { get; set; }
        public int PlayerId { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
