//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecouverteEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoTag
    {
        public int IDPhoto { get; set; }
        public int IDTag { get; set; }
        public System.DateTime DateCreation { get; set; }
    
        public virtual Photo Photo { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
