//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecouverteEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ladiagonale_poulposhi_database_rec_version_devEntities : DbContext
    {
        public ladiagonale_poulposhi_database_rec_version_devEntities()
            : base("name=ladiagonale_poulposhi_database_rec_version_devEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BasicAuthentications> BasicAuthentications { get; set; }
        public virtual DbSet<Octopuses> Octopuses { get; set; }
        public virtual DbSet<Players> Players { get; set; }
    }
}
